---
title: "TEST"
author: "Tristrim Cummings"
date: "11/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Workshop 3

```{r}
#Ctrl+Alt+I = generateR chunk
library(tidyverse)
library(janitor)
library(skimr)


survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

write_csv(survey,file="survey_data.csv")

survey%>%glimpse() #summary of the data
survey%>%skim() #review the data and report missing data and statistics

survey %>%
  top_n(survey, 20)


survey%>%head()

shortdata<-survey_IT_au %>%
  transmute(total_pay = annual_salary+other_monetary_comp)
```

### Data Wrangling


#### Filter

```{r}
survey%>%
  filter(country == "Australia")

survey_IT_au <- survey%>%
  filter(country=="Australia"|country=="australia"|country=="australi")%>%
  filter(industry=="Computing or Tech" & annual_salary>80000)

survey%>%
  filter(gender!="Man")

 
```

### Select & Arrange

```{r}
survey_IT_au%>%
  select(how_old_are_you, job_title, annual_salary)%>%
  arrange(desc(annual_salary))

survey%>%
  distinct(industry)

survey_IT_au%>%
  select(-industry)

survey_IT_au%>%
  count(highest_level_of_education_completed, sort = TRUE)


survey_IT_au%>%
  count(gender, city, sort=TRUE)

New_data<-survey_IT_au%>%add_count(highest_level_of_education_completed, sort = TRUE)



survey%>%
  count(gender,industry, sort = TRUE)


  


```


#### `mutate` vs `transmute`

```{r}

class(survey_IT_au$annual_salary)

survey_IT_au %>%
  mutate(total_salary=annual_salary+other_monetary_comp)

survey_IT_au<- survey_IT_au %>%
  mutate(avr_salary=mean(annual_salary))

#survey_IT_au_groupd <- survey_IT_au %>%
 # group_by(city)%>%
  #mutate(max_salary=max(annual_salary))
  #select(how_old_are_you, job_title, city, annual_salary, avr_salary, max_salary)%>&
   # ungroup()

survey_IT_au%>%
  summarise(min_salary=min(annual_salary))
  

survey_IT_au%>%
  group_by(gender)%>%
  summarise(min_salary=min(annual_salary))

survey_IT_au%>%
  group_by(gender)%>%
  summarise(min_salary=min(annual_salary),
            max_salary=max(annual_salary),
            avr_salary=mean(annual_salary))%>%
  relocate(max_salary, .after=avr_salary)
  ungroup()


survey_IT_au%>%
  mutate(age=parse_number(how_old_are_you))
  

survey_IT_au <- survey_IT_au%>%
  mutate(experience=parse_number(overall_years_of_professional_experience))

survey_IT_au %>%
  mutate(su_analyst = case_when(job_title == "Business Analyst" ~ "Yes", T ~ "No"))
  
```



# David Robinson's tricks


```{r}
#Number 1 Count
survey%>%
  count(country, sort = TRUE, state, name="Counrty/State Count")

survey%>%
  count(country, state)

#--------------------------------------------------------------
#Number 2 - create a new variable in count

survey%>%
  count(grouped_salary = annual_salary + other_monetary_comp, sort = TRUE)

#--------------------------------------------------------------
#Number 3 - add_count - add a column that counts

survey_IT_au%>%
  group_by(gender)%>%
  summarise(min_salary=min(annual_salary),
            max_salary=max(annual_salary),
            avr_salary=mean(annual_salary))%>%
  add_count(gender)

#--------------------------------------------------------------
#Number 4 - Summarise - to create a list column
# I dont understand this function

#--------------------------------------------------------------
#Number 5 - factor reorder

#--------------------------------------------------------------
#Number 6 - factor lump


#--------------------------------------------------------------
#Number 7 - scale xy log10()
#ggplot2 function


#--------------------------------------------------------------
#Number 8 - Crossing

#--------------------------------------------------------------
#Number 9 - separate
survey_IT_au%>%
  separate(how_old_are_you,c("low_age", "high_age"))

#--------------------------------------------------------------
#Number 10 - extract

survey_IT_au%>%
  extract(overall_years_of_professional_experience, c("Low_Year", "High_Year", "Time_scale")) #I dont know how to set up the expression to extract


```



# Extra Additional Tricks

```{r}
#1 - create new column in a count
survey%>%
  count(country, sort = TRUE, state, name="Counrty/State Count")

# 2. Sample and randomly shuffle data with slice_sample()

survey %>% 
  slice_sample(n=2, )


# 3. Create a date column specifying year, month, and day

# 4. Parse numbers with parse_number()

survey_IT_au %>% 
  parse_number(how_old_are_you) #dont know how this works


# 5. Select columns with starts_with, ends_with, etc.

survey %>% 
  select(starts_with("how", ignore.case = TRUE))

survey %>% 
  select(ends_with("title", ignore.case = TRUE))

# 6. case_when to create or change a column when conditions are met

survey %>% 
  mutate(salary_band = case_when(
                        annual_salary <= 100000 ~ "Low", 
                        annual_salary >100000 ~ "High"))


# 7. str_replace_all to find and replace multiple options at once

survey_IT_au%>% 
  str_replace_all(c("Man" = "male", "Woman" = "Female"))


# 8. Transmute to create or change columns and keep only those columns
survey %>% 
  transmute(Monthly_salary = annual_salary/12)


# 9. Use pipes %>% everywhere including inside mutates


# 10. Filter groups without making a new column


# 11. Split a string into columns based on a regular expression

survey_IT_au%>%
  separate(how_old_are_you,c("low_age", "high_age"))


# 12. semi_join to pick only rows from the first table which are matched in the second table
# 13. anti_join to pick only rows from the first table which are NOT matched in the second table
# 14. fct_reorder to sort bar charts
# 15. coord_flip to display counts more beautifully
# 16. fct_lump to lump some factor levels into "Other"
# 17. Generate all combinations using crossing
# 18. Create functions that take column names with double curly braces


```


